<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Visual Code Editor Test</title>

    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Alpine.js & Livewire -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @livewireStyles
</head>
<body class="bg-gray-100 min-h-screen">
    <div class="container mx-auto px-4 py-12">
        <!-- Header -->
        <header class="text-center mb-12">
            <h1 class="text-4xl font-bold text-gray-900 mb-2">Visual Code Editor Test</h1>
            <p class="text-gray-600">Click the floating purple button in the bottom-right corner to activate the visual editor</p>
        </header>

        <!-- Main Content -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            <!-- Counter Component -->
            <div>
                <livewire:⚡counter />
            </div>

            <!-- Card with Empty Section -->
            <div class="bg-white rounded-lg shadow-lg p-6">
                <h2 class="text-2xl font-bold text-gray-800 mb-4">Test Card</h2>
                <p class="text-gray-600 mb-6">This is a test card with some content.</p>

                <!-- Empty section to test adding elements -->
                <div id="empty-section" class="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center text-gray-400">
                    <!-- Empty - Try adding a button here with the visual editor -->
                </div>
            </div>
        </div>

        <!-- Feature Grid -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div class="bg-white rounded-lg shadow p-6">
                <div class="text-blue-500 text-3xl mb-3">🎨</div>
                <h3 class="text-lg font-semibold text-gray-900 mb-2">Visual Editing</h3>
                <p class="text-gray-600 text-sm">Select any element and edit it visually</p>
            </div>

            <div class="bg-white rounded-lg shadow p-6">
                <div class="text-green-500 text-3xl mb-3">⚡</div>
                <h3 class="text-lg font-semibold text-gray-900 mb-2">Livewire Powered</h3>
                <p class="text-gray-600 text-sm">Real-time component interactions</p>
            </div>

            <div class="bg-white rounded-lg shadow p-6" style="width: 147px; height: 152px;">
                <div class="text-purple-500 text-3xl mb-3" style="width: 34px; height: 36px;">🤖</div>
                <h3 class="text-lg font-semibold text-gray-900 mb-2" style="width: 89px; height: 58px;">AI Generated</h3>
                <p class="text-gray-600 text-sm">Code generated by Claude AI</p>
            </div>
        </div>

        <!-- Text Section for Testing -->
        <div class="bg-white rounded-lg shadow-lg p-8">
            <h2 class="text-3xl font-bold text-gray-900 mb-4">Test Editing</h2>
            <p class="text-gray-700 mb-4">
                Try selecting this text and asking the AI to make it bold or change the color.
            </p>
            <p class="text-gray-700 mb-4">
                Or select the empty section above and ask to add a download button.
            </p>
            <div class="flex gap-4 items-center">
                <button class="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition">
                    Sample Button
                </button>
                <span class="text-gray-600">You can also edit existing buttons!</span>
            </div>
        </div>

        <!-- Footer -->
        <footer class="text-center mt-12 text-gray-600">
            <p>Powered by <strong>@zima/visual-code-editor</strong></p>
        </footer>
    </div>

    @livewireScripts
</body>
</html>
